// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD80D0V0oBzTTwklyZsK1280KSFwOthFU',
    appId: '1:883028401432:android:64014e1fed417664c9126d',
    messagingSenderId: '883028401432',
    projectId: 'sripon-c303b',
    storageBucket: 'sripon-c303b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWofMvppSrBu3CyeUECqELOLaCEMdqi54',
    appId: '1:883028401432:ios:f5a4b2ee9201fdb9c9126d',
    messagingSenderId: '883028401432',
    projectId: 'sripon-c303b',
    storageBucket: 'sripon-c303b.firebasestorage.app',
    androidClientId: '883028401432-esc73p8in39ogivog29ep1iaaqkmm1qu.apps.googleusercontent.com',
    iosClientId: '883028401432-e5aclb806j499ldcmq262d6jvj5s03pu.apps.googleusercontent.com',
    iosBundleId: 'com.trisentricai.sreepon',
  );
}
